; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool on Wed Aug 29 2018 03:48:52 GMT-0400 (Eastern Daylight Time)
; Wait for set temperatures to be reached
M116 P0